tabs:
  tab_1:
    type: text
  tab_2:
    type: text
  tab_3:
    type: text
  tab_4:
    type: text

routes:
  ajax_find_by_name:
    pattern:  /ajax_find_by_name/
    defaults: { _controller: plugins\riProduct\ProductController::ajaxFindByNameAction }
 